# Generated by Django 3.2.8 on 2021-10-23 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_resultwork_distinguished_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultwork',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
