# Generated by Django 3.2.8 on 2021-10-24 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_resultwork_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultwork',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
